<?php $pageTitle = 'Labour Management'; ?>
<div class="d-flex flex-wrap justify-content-between align-items-center mb-4 gap-2">
    <div><h2 class="h4 mb-1">Labour Management</h2><p class="text-muted mb-0">Construction workforce and daily site progress.</p></div>
    <div class="d-flex gap-2"><a class="btn btn-outline-primary" href="<?= e(app_url('/labour/attendance')) ?>">Attendance</a><a class="btn btn-accent" href="<?= e(app_url('/labour/work')) ?>">Today's Work</a></div>
</div>
<div class="row g-3 mb-4">
    <?php $cards = [["Today's Labour", $metrics['total'], 'bi-person-workspace'], ['Present', $metrics['present'], 'bi-person-check'], ['Absent', $metrics['absent'], 'bi-person-x'], ['Half Day', $metrics['half_day'], 'bi-person-dash'], ['Total Labour Cost', format_currency($metrics['cost']), 'bi-cash-stack'], ['Completed Work', $metrics['completed'], 'bi-check2-circle'], ['Delayed Activities', $metrics['delayed'], 'bi-exclamation-triangle'], ['Project Progress', number_format($metrics['progress'], 1) . '%', 'bi-graph-up-arrow']]; ?>
    <?php foreach ($cards as $card): ?><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="d-flex justify-content-between"><span class="text-muted small"><?= e($card[0]) ?></span><i class="bi <?= e($card[2]) ?> text-primary"></i></div><div class="fs-4 fw-semibold mt-2"><?= e((string)$card[1]) ?></div></div></div></div><?php endforeach; ?>
</div>
<div class="row g-4 mb-4">
    <div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-body"><h3 class="h6">Daily Labour Attendance</h3><canvas id="labourAttendanceChart" height="140"></canvas></div></div></div>
    <div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-body"><h3 class="h6">Work Completion Trend</h3><canvas id="labourProgressChart" height="140"></canvas></div></div></div>
</div>
<div class="card border-0 shadow-sm"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h3 class="h6 mb-0">Recent Site Work</h3><a href="<?= e(app_url('/labour/export/work/csv')) ?>" class="btn btn-sm btn-outline-secondary">Export CSV</a></div><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Date</th><th>Project</th><th>Activity</th><th>Contractor</th><th>Progress</th><th>Status</th></tr></thead><tbody><?php foreach ($recentWork as $row): ?><tr><td><?= e(format_date($row['date'])) ?></td><td><?= e($row['project_name'] ?? '-') ?></td><td><?= e($row['activity']) ?></td><td><?= e($row['contractor_name'] ?? '-') ?></td><td><?= e(number_format((float)$row['completion_percentage'], 1)) ?>%</td><td><span class="badge text-bg-<?= $row['status'] === 'Delayed' ? 'danger' : ($row['status'] === 'Completed' ? 'success' : 'warning') ?>"><?= e($row['status']) ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<script>
new Chart(document.getElementById('labourAttendanceChart'), {type:'line', data:{labels:<?= json_encode(array_column($attendanceTrend, 'date')) ?>, datasets:[{label:'Present',data:<?= json_encode(array_map('intval', array_column($attendanceTrend, 'present'))) ?>,borderColor:'#159a82',backgroundColor:'rgba(21,154,130,.12)',fill:true},{label:'Absent',data:<?= json_encode(array_map('intval', array_column($attendanceTrend, 'absent'))) ?>,borderColor:'#dc3545',fill:false}]}, options:{responsive:true, maintainAspectRatio:false}});
new Chart(document.getElementById('labourProgressChart'), {type:'bar', data:{labels:<?= json_encode(array_column($progressTrend, 'date')) ?>, datasets:[{label:'Completion %',data:<?= json_encode(array_map('floatval', array_column($progressTrend, 'progress'))) ?>,backgroundColor:'#3b6edc'}]}, options:{responsive:true, maintainAspectRatio:false, scales:{y:{beginAtZero:true,max:100}}}});
</script>
