<?php

declare(strict_types=1);

return [
    'users' => [
        'label' => 'Users',
        'table' => 'users',
        'route' => '/users',
        'fields' => [
            ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'required' => true],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'required' => true],
            ['name' => 'password', 'label' => 'Password', 'type' => 'password', 'required' => true],
            ['name' => 'phone', 'label' => 'Phone', 'type' => 'text'],
            ['name' => 'role', 'label' => 'Role', 'type' => 'select', 'options' => ['Super Admin', 'Admin', 'Sales Manager', 'Sales Executive', 'Accountant']],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Active', 'Inactive']],
        ],
        'columns' => ['name', 'email', 'role', 'status'],
    ],
    'leads' => [
        'label' => 'Leads',
        'table' => 'leads',
        'route' => '/leads',
        'filters' => [
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['New', 'Contacted', 'Follow-up', 'Site Visit', 'Negotiation', 'Booked', 'Lost']],
            ['name' => 'source', 'label' => 'Lead Source', 'type' => 'select', 'options' => ['Facebook', 'Instagram', 'Google Ads', 'Website', 'Walk-in', 'Referral', 'WhatsApp', 'Phone Call']],
            ['name' => 'assigned_to', 'label' => 'Assigned Executive', 'type' => 'text'],
        ],
        'fields' => [
            ['name' => 'name', 'label' => 'Customer Name', 'type' => 'text', 'required' => true],
            ['name' => 'mobile', 'label' => 'Mobile Number', 'type' => 'text', 'required' => true],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email'],
            ['name' => 'source', 'label' => 'Lead Source', 'type' => 'select', 'options' => ['Facebook', 'Instagram', 'Google Ads', 'Website', 'Walk-in', 'Referral', 'WhatsApp', 'Phone Call']],
            ['name' => 'property_type', 'label' => 'Property Type', 'type' => 'select', 'options' => ['Apartment', 'Villa', 'Plot', 'Commercial']],
            ['name' => 'location', 'label' => 'Preferred Location', 'type' => 'text'],
            ['name' => 'assigned_to', 'label' => 'Assigned Sales Executive', 'type' => 'text'],
            ['name' => 'budget', 'label' => 'Budget', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['New', 'Contacted', 'Follow-up', 'Site Visit', 'Negotiation', 'Booked', 'Lost']],
            ['name' => 'ai_score', 'label' => 'AI Lead Score', 'type' => 'number'],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'columns' => ['name', 'mobile', 'source', 'property_type', 'location', 'status', 'assigned_to', 'budget'],
    ],
    'customers' => [
        'label' => 'Customers',
        'table' => 'customers',
        'route' => '/customers',
        'filters' => [
            ['name' => 'occupation', 'label' => 'Occupation', 'type' => 'text'],
            ['name' => 'notes', 'label' => 'Remarks', 'type' => 'text'],
        ],
        'fields' => [
            ['name' => 'name', 'label' => 'Customer Name', 'type' => 'text', 'required' => true],
            ['name' => 'mobile', 'label' => 'Mobile', 'type' => 'text'],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email'],
            ['name' => 'address', 'label' => 'Address', 'type' => 'textarea'],
            ['name' => 'aadhaar', 'label' => 'Aadhaar Number', 'type' => 'text'],
            ['name' => 'pan', 'label' => 'PAN Number', 'type' => 'text'],
            ['name' => 'occupation', 'label' => 'Occupation', 'type' => 'text'],
            ['name' => 'notes', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['name', 'mobile', 'email', 'occupation', 'aadhaar'],
    ],
    'projects' => [
        'label' => 'Projects',
        'table' => 'projects',
        'route' => '/projects',
        'filters' => [
            ['name' => 'status', 'label' => 'Project Status', 'type' => 'select', 'options' => ['Planning', 'Active', 'On Hold', 'Completed']],
            ['name' => 'location', 'label' => 'Location', 'type' => 'text'],
        ],
        'fields' => [
            ['name' => 'name', 'label' => 'Project Name', 'type' => 'text', 'required' => true],
            ['name' => 'builder', 'label' => 'Builder', 'type' => 'text'],
            ['name' => 'location', 'label' => 'Location', 'type' => 'text'],
            ['name' => 'amenities', 'label' => 'Amenities', 'type' => 'textarea'],
            ['name' => 'brochure', 'label' => 'Brochure', 'type' => 'file'],
            ['name' => 'gallery', 'label' => 'Gallery', 'type' => 'file'],
            ['name' => 'master_plan', 'label' => 'Master Plan', 'type' => 'file'],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea'],
            ['name' => 'status', 'label' => 'Project Status', 'type' => 'select', 'options' => ['Planning', 'Active', 'On Hold', 'Completed']],
        ],
        'columns' => ['name', 'builder', 'location', 'status'],
    ],
    'flats' => [
        'label' => 'Flats',
        'table' => 'flats',
        'route' => '/flats',
        'filters' => [
            ['name' => 'availability', 'label' => 'Status', 'type' => 'select', 'options' => ['Available', 'Reserved', 'Sold']],
            ['name' => 'facing', 'label' => 'Facing', 'type' => 'text'],
        ],
        'fields' => [
            ['name' => 'project_id', 'label' => 'Project ID', 'type' => 'number'],
            ['name' => 'flat_number', 'label' => 'Flat Number', 'type' => 'text'],
            ['name' => 'floor', 'label' => 'Floor Number', 'type' => 'text'],
            ['name' => 'area', 'label' => 'Area (Sq.ft)', 'type' => 'number'],
            ['name' => 'facing', 'label' => 'Facing', 'type' => 'text'],
            ['name' => 'price', 'label' => 'Price', 'type' => 'number'],
            ['name' => 'availability', 'label' => 'Status', 'type' => 'select', 'options' => ['Available', 'Reserved', 'Sold']],
            ['name' => 'parking', 'label' => 'Car Parking', 'type' => 'text'],
        ],
        'columns' => ['flat_number', 'floor', 'area', 'price', 'availability', 'facing'],
    ],
    'sitevisits' => [
        'label' => 'Site Visits',
        'table' => 'site_visits',
        'route' => '/site-visits',
        'filters' => [
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Scheduled', 'Completed', 'Missed']],
            ['name' => 'scheduled_at', 'label' => 'Visit Date', 'type' => 'date'],
        ],
        'fields' => [
            ['name' => 'lead_id', 'label' => 'Lead ID', 'type' => 'number'],
            ['name' => 'customer_id', 'label' => 'Customer ID', 'type' => 'number'],
            ['name' => 'executive_id', 'label' => 'Executive ID', 'type' => 'number'],
            ['name' => 'scheduled_at', 'label' => 'Visit Date', 'type' => 'datetime-local'],
            ['name' => 'feedback', 'label' => 'Feedback', 'type' => 'textarea'],
            ['name' => 'next_followup_at', 'label' => 'Next Follow-up', 'type' => 'datetime-local'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Scheduled', 'Completed', 'Missed']],
        ],
        'columns' => ['lead_id', 'customer_id', 'executive_id', 'scheduled_at', 'status'],
    ],
    'bookings' => [
        'label' => 'Bookings',
        'table' => 'bookings',
        'route' => '/bookings',
        'filters' => [
            ['name' => 'status', 'label' => 'Booking Status', 'type' => 'select', 'options' => ['Lead', 'Site Visit', 'Quotation', 'Booked', 'Payment', 'Agreement', 'Registration']],
            ['name' => 'booking_date', 'label' => 'Booking Date', 'type' => 'date'],
        ],
        'fields' => [
            ['name' => 'lead_id', 'label' => 'Lead ID', 'type' => 'number'],
            ['name' => 'customer_id', 'label' => 'Customer ID', 'type' => 'number'],
            ['name' => 'project_id', 'label' => 'Project ID', 'type' => 'number'],
            ['name' => 'flat_id', 'label' => 'Flat ID', 'type' => 'number'],
            ['name' => 'booking_date', 'label' => 'Booking Date', 'type' => 'date'],
            ['name' => 'booking_amount', 'label' => 'Booking Amount', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Booking Status', 'type' => 'select', 'options' => ['Lead', 'Site Visit', 'Quotation', 'Booked', 'Payment', 'Agreement', 'Registration']],
            ['name' => 'notes', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['lead_id', 'customer_id', 'project_id', 'flat_id', 'booking_amount', 'status', 'booking_date'],
    ],
    'quotations' => [
        'label' => 'Quotations',
        'table' => 'quotations',
        'route' => '/quotations',
        'filters' => [
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Approved', 'Rejected']],
            ['name' => 'valid_until', 'label' => 'Valid Until', 'type' => 'date'],
        ],
        'fields' => [
            ['name' => 'lead_id', 'label' => 'Lead ID', 'type' => 'number'],
            ['name' => 'customer_id', 'label' => 'Customer ID', 'type' => 'number'],
            ['name' => 'project_id', 'label' => 'Project ID', 'type' => 'number'],
            ['name' => 'flat_id', 'label' => 'Flat ID', 'type' => 'number'],
            ['name' => 'amount', 'label' => 'Amount', 'type' => 'number'],
            ['name' => 'valid_until', 'label' => 'Valid Until', 'type' => 'date'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Approved', 'Rejected']],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'columns' => ['lead_id', 'customer_id', 'project_id', 'flat_id', 'amount', 'valid_until', 'status'],
    ],
    'payments' => [
        'label' => 'Payments',
        'table' => 'payments',
        'route' => '/payments',
        'filters' => [
            ['name' => 'status', 'label' => 'Payment Status', 'type' => 'select', 'options' => ['Pending', 'Partially Paid', 'Paid', 'Overdue']],
            ['name' => 'payment_mode', 'label' => 'Payment Mode', 'type' => 'text'],
        ],
        'fields' => [
            ['name' => 'booking_id', 'label' => 'Booking ID', 'type' => 'number'],
            ['name' => 'customer_id', 'label' => 'Customer ID', 'type' => 'number'],
            ['name' => 'amount', 'label' => 'Amount', 'type' => 'number'],
            ['name' => 'payment_mode', 'label' => 'Payment Mode', 'type' => 'text'],
            ['name' => 'due_date', 'label' => 'Due Date', 'type' => 'date'],
            ['name' => 'paid_at', 'label' => 'Paid At', 'type' => 'datetime-local'],
            ['name' => 'receipt_no', 'label' => 'Receipt Number', 'type' => 'text'],
            ['name' => 'invoice_path', 'label' => 'Invoice File', 'type' => 'file'],
            ['name' => 'status', 'label' => 'Payment Status', 'type' => 'select', 'options' => ['Pending', 'Partially Paid', 'Paid', 'Overdue']],
            ['name' => 'notes', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['booking_id', 'customer_id', 'amount', 'payment_mode', 'receipt_no', 'status'],
    ],
    'agreements' => [
        'label' => 'Agreements',
        'table' => 'agreements',
        'route' => '/agreements',
        'filters' => [
            ['name' => 'status', 'label' => 'Agreement Status', 'type' => 'select', 'options' => ['Draft', 'Signed', 'Registered']],
            ['name' => 'agreement_date', 'label' => 'Agreement Date', 'type' => 'date'],
        ],
        'fields' => [
            ['name' => 'booking_id', 'label' => 'Booking ID', 'type' => 'number'],
            ['name' => 'customer_id', 'label' => 'Customer ID', 'type' => 'number'],
            ['name' => 'agreement_number', 'label' => 'Agreement Number', 'type' => 'text'],
            ['name' => 'agreement_date', 'label' => 'Agreement Date', 'type' => 'date'],
            ['name' => 'document_path', 'label' => 'Agreement File', 'type' => 'file'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Signed', 'Registered']],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'columns' => ['booking_id', 'customer_id', 'agreement_number', 'agreement_date', 'status'],
    ],
    'registrations' => [
        'label' => 'Registrations',
        'table' => 'registrations',
        'route' => '/registrations',
        'filters' => [
            ['name' => 'status', 'label' => 'Registration Status', 'type' => 'select', 'options' => ['Pending', 'Completed', 'Rejected']],
            ['name' => 'registration_date', 'label' => 'Registration Date', 'type' => 'date'],
        ],
        'fields' => [
            ['name' => 'booking_id', 'label' => 'Booking ID', 'type' => 'number'],
            ['name' => 'customer_id', 'label' => 'Customer ID', 'type' => 'number'],
            ['name' => 'registration_date', 'label' => 'Registration Date', 'type' => 'date'],
            ['name' => 'document_path', 'label' => 'Registration File', 'type' => 'file'],
            ['name' => 'status', 'label' => 'Registration Status', 'type' => 'select', 'options' => ['Pending', 'Completed', 'Rejected']],
            ['name' => 'remarks', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['booking_id', 'customer_id', 'registration_date', 'status'],
    ],
    'receipts' => [
        'label' => 'Receipts',
        'table' => 'receipts',
        'route' => '/receipts',
        'filters' => [
            ['name' => 'receipt_no', 'label' => 'Receipt No', 'type' => 'text'],
            ['name' => 'received_at', 'label' => 'Received Date', 'type' => 'date'],
        ],
        'fields' => [
            ['name' => 'payment_id', 'label' => 'Payment ID', 'type' => 'number'],
            ['name' => 'customer_id', 'label' => 'Customer ID', 'type' => 'number'],
            ['name' => 'receipt_no', 'label' => 'Receipt Number', 'type' => 'text'],
            ['name' => 'amount', 'label' => 'Amount', 'type' => 'number'],
            ['name' => 'received_at', 'label' => 'Received At', 'type' => 'datetime-local'],
            ['name' => 'payment_mode', 'label' => 'Payment Mode', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'Completed']],
            ['name' => 'notes', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['payment_id', 'customer_id', 'receipt_no', 'amount', 'status'],
    ],
    'cash_books' => [
        'label' => 'Cash Book',
        'table' => 'cash_books',
        'route' => '/cash-books',
        'filters' => [
            ['name' => 'date', 'label' => 'Date', 'type' => 'date'],
            ['name' => 'type', 'label' => 'Entry Type', 'type' => 'select', 'options' => ['Receipt', 'Payment']],
        ],
        'fields' => [
            ['name' => 'date', 'label' => 'Date', 'type' => 'date'],
            ['name' => 'particulars', 'label' => 'Particulars', 'type' => 'text'],
            ['name' => 'debit', 'label' => 'Debit', 'type' => 'number'],
            ['name' => 'credit', 'label' => 'Credit', 'type' => 'number'],
            ['name' => 'balance', 'label' => 'Balance', 'type' => 'number'],
            ['name' => 'type', 'label' => 'Entry Type', 'type' => 'select', 'options' => ['Receipt', 'Payment']],
            ['name' => 'remarks', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['date', 'particulars', 'debit', 'credit', 'balance'],
    ],
    'bank_books' => [
        'label' => 'Bank Book',
        'table' => 'bank_books',
        'route' => '/bank-books',
        'filters' => [
            ['name' => 'date', 'label' => 'Date', 'type' => 'date'],
            ['name' => 'bank_name', 'label' => 'Bank', 'type' => 'text'],
        ],
        'fields' => [
            ['name' => 'date', 'label' => 'Date', 'type' => 'date'],
            ['name' => 'bank_name', 'label' => 'Bank Name', 'type' => 'text'],
            ['name' => 'particulars', 'label' => 'Particulars', 'type' => 'text'],
            ['name' => 'debit', 'label' => 'Debit', 'type' => 'number'],
            ['name' => 'credit', 'label' => 'Credit', 'type' => 'number'],
            ['name' => 'balance', 'label' => 'Balance', 'type' => 'number'],
            ['name' => 'remarks', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['date', 'bank_name', 'particulars', 'debit', 'credit', 'balance'],
    ],
    'income_expenses' => [
        'label' => 'Income & Expense',
        'table' => 'income_expenses',
        'route' => '/income-expenses',
        'filters' => [
            ['name' => 'type', 'label' => 'Type', 'type' => 'select', 'options' => ['Income', 'Expense']],
            ['name' => 'category', 'label' => 'Category', 'type' => 'text'],
        ],
        'fields' => [
            ['name' => 'type', 'label' => 'Type', 'type' => 'select', 'options' => ['Income', 'Expense'], 'required' => true],
            ['name' => 'category', 'label' => 'Category', 'type' => 'text'],
            ['name' => 'amount', 'label' => 'Amount', 'type' => 'number', 'required' => true],
            ['name' => 'date', 'label' => 'Date', 'type' => 'date', 'required' => true],
            ['name' => 'gst_amount', 'label' => 'GST Amount', 'type' => 'number'],
            ['name' => 'tds_amount', 'label' => 'TDS Amount', 'type' => 'number'],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Posted', 'Settled']],
        ],
        'columns' => ['date', 'type', 'category', 'amount', 'status'],
    ],
    'gst_reports' => [
        'label' => 'GST Reports',
        'table' => 'gst_reports',
        'route' => '/gst-reports',
        'filters' => [
            ['name' => 'period', 'label' => 'Period', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Filed', 'Paid']],
        ],
        'fields' => [
            ['name' => 'period', 'label' => 'Period', 'type' => 'text'],
            ['name' => 'gst_collected', 'label' => 'GST Collected', 'type' => 'number'],
            ['name' => 'gst_input', 'label' => 'GST Input', 'type' => 'number'],
            ['name' => 'payable', 'label' => 'Payable', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Filed', 'Paid']],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'columns' => ['period', 'gst_collected', 'gst_input', 'payable', 'status'],
    ],
    'tds_reports' => [
        'label' => 'TDS Reports',
        'table' => 'tds_reports',
        'route' => '/tds-reports',
        'filters' => [
            ['name' => 'period', 'label' => 'Period', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Filed', 'Paid']],
        ],
        'fields' => [
            ['name' => 'period', 'label' => 'Period', 'type' => 'text'],
            ['name' => 'tds_collected', 'label' => 'TDS Collected', 'type' => 'number'],
            ['name' => 'payable', 'label' => 'Payable', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Filed', 'Paid']],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'columns' => ['period', 'tds_collected', 'payable', 'status'],
    ],
    'followups' => [
        'label' => 'Follow-ups',
        'table' => 'followups',
        'route' => '/followups',
        'filters' => [
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'Completed', 'Skipped']],
            ['name' => 'followup_at', 'label' => 'Follow-up Date', 'type' => 'date'],
        ],
        'fields' => [
            ['name' => 'lead_id', 'label' => 'Lead ID', 'type' => 'number'],
            ['name' => 'customer_id', 'label' => 'Customer ID', 'type' => 'number'],
            ['name' => 'assigned_to', 'label' => 'Assigned To', 'type' => 'text'],
            ['name' => 'followup_at', 'label' => 'Follow-up At', 'type' => 'datetime-local'],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'Completed', 'Skipped']],
        ],
        'columns' => ['lead_id', 'customer_id', 'assigned_to', 'followup_at', 'status'],
    ],
    'documents' => [
        'label' => 'Documents',
        'table' => 'documents',
        'route' => '/documents',
        'filters' => [
            ['name' => 'document_type', 'label' => 'Document Type', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'Verified', 'Rejected']],
        ],
        'fields' => [
            ['name' => 'customer_id', 'label' => 'Customer ID', 'type' => 'number'],
            ['name' => 'booking_id', 'label' => 'Booking ID', 'type' => 'number'],
            ['name' => 'document_type', 'label' => 'Document Type', 'type' => 'text'],
            ['name' => 'file_path', 'label' => 'File', 'type' => 'file'],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'Verified', 'Rejected']],
        ],
        'columns' => ['customer_id', 'booking_id', 'document_type', 'status'],
    ],
    'notifications' => [
        'label' => 'Notifications',
        'table' => 'notifications',
        'route' => '/notifications',
        'filters' => [
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Queued', 'Sent', 'Failed']],
            ['name' => 'channel', 'label' => 'Channel', 'type' => 'select', 'options' => ['WhatsApp', 'Email', 'SMS', 'In-App']],
        ],
        'fields' => [
            ['name' => 'user_id', 'label' => 'User ID', 'type' => 'number'],
            ['name' => 'channel', 'label' => 'Channel', 'type' => 'select', 'options' => ['WhatsApp', 'Email', 'SMS', 'In-App']],
            ['name' => 'title', 'label' => 'Title', 'type' => 'text'],
            ['name' => 'message', 'label' => 'Message', 'type' => 'textarea'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Queued', 'Sent', 'Failed']],
        ],
        'columns' => ['user_id', 'channel', 'title', 'status'],
    ],
    'activities' => [
        'label' => 'Activities',
        'table' => 'activities',
        'route' => '/activities',
        'filters' => [
            ['name' => 'module', 'label' => 'Module', 'type' => 'text'],
            ['name' => 'action', 'label' => 'Action', 'type' => 'text'],
        ],
        'fields' => [
            ['name' => 'user_id', 'label' => 'User ID', 'type' => 'number'],
            ['name' => 'module', 'label' => 'Module', 'type' => 'text'],
            ['name' => 'action', 'label' => 'Action', 'type' => 'text'],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea'],
        ],
        'columns' => ['user_id', 'module', 'action'],
    ],
    'contractors' => [
        'label' => 'Contractors',
        'table' => 'contractors',
        'route' => '/contractors',
        'permissions' => ['Super Admin', 'Admin', 'HR', 'Project Manager', 'Site Engineer', 'Supervisor'],
        'fields' => [
            ['name' => 'name', 'label' => 'Contractor Name', 'type' => 'text', 'required' => true],
            ['name' => 'mobile', 'label' => 'Mobile', 'type' => 'text'],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email'],
            ['name' => 'address', 'label' => 'Address', 'type' => 'textarea'],
            ['name' => 'trade', 'label' => 'Primary Trade', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Active', 'Inactive']],
            ['name' => 'remarks', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['name', 'mobile', 'trade', 'status'],
    ],
    'labours' => [
        'label' => 'Labour Master',
        'table' => 'labours',
        'route' => '/labours',
        'permissions' => ['Super Admin', 'Admin', 'HR', 'Project Manager', 'Site Engineer', 'Supervisor'],
        'fields' => [
            ['name' => 'labour_id', 'label' => 'Labour ID', 'type' => 'text', 'required' => true],
            ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'required' => true],
            ['name' => 'mobile', 'label' => 'Mobile', 'type' => 'text'],
            ['name' => 'address', 'label' => 'Address', 'type' => 'textarea'],
            ['name' => 'aadhaar', 'label' => 'Aadhaar', 'type' => 'text'],
            ['name' => 'contractor_id', 'label' => 'Contractor ID', 'type' => 'number'],
            ['name' => 'trade', 'label' => 'Trade', 'type' => 'text', 'required' => true],
            ['name' => 'daily_wage', 'label' => 'Daily Wage', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Active', 'Inactive']],
            ['name' => 'joining_date', 'label' => 'Joining Date', 'type' => 'date'],
            ['name' => 'remarks', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['labour_id', 'name', 'trade', 'daily_wage', 'status'],
    ],
    'employees' => [
        'label' => 'Employees',
        'table' => 'employees',
        'route' => '/employees',
        'permissions' => ['Super Admin', 'Admin', 'HR'],
        'fields' => [
            ['name' => 'employee_id', 'label' => 'Employee ID', 'type' => 'text', 'required' => true],
            ['name' => 'user_id', 'label' => 'User ID', 'type' => 'number'],
            ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'required' => true],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email'],
            ['name' => 'phone', 'label' => 'Phone', 'type' => 'text'],
            ['name' => 'department', 'label' => 'Department', 'type' => 'text'],
            ['name' => 'designation', 'label' => 'Designation', 'type' => 'text'],
            ['name' => 'manager', 'label' => 'Manager', 'type' => 'text'],
            ['name' => 'salary', 'label' => 'Salary', 'type' => 'number'],
            ['name' => 'joining_date', 'label' => 'Joining Date', 'type' => 'date'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Active', 'Inactive', 'On Leave']],
        ],
        'columns' => ['employee_id', 'name', 'department', 'designation', 'status'],
    ],
    'leave_requests' => [
        'label' => 'Leave Requests',
        'table' => 'leave_requests',
        'route' => '/leave-requests',
        'permissions' => ['Super Admin', 'Admin', 'HR'],
        'fields' => [
            ['name' => 'employee_id', 'label' => 'Employee ID', 'type' => 'number', 'required' => true],
            ['name' => 'leave_type', 'label' => 'Leave Type', 'type' => 'text', 'required' => true],
            ['name' => 'start_date', 'label' => 'Start Date', 'type' => 'date', 'required' => true],
            ['name' => 'end_date', 'label' => 'End Date', 'type' => 'date', 'required' => true],
            ['name' => 'days', 'label' => 'Days', 'type' => 'number'],
            ['name' => 'reason', 'label' => 'Reason', 'type' => 'textarea'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'Approved', 'Rejected']],
            ['name' => 'manager_comment', 'label' => 'Manager Comment', 'type' => 'textarea'],
        ],
        'columns' => ['employee_id', 'leave_type', 'start_date', 'end_date', 'status'],
    ],
    'payrolls' => [
        'label' => 'Payroll',
        'table' => 'payrolls',
        'route' => '/payrolls',
        'permissions' => ['Super Admin', 'Admin', 'HR', 'Accountant'],
        'fields' => [
            ['name' => 'employee_id', 'label' => 'Employee ID', 'type' => 'number', 'required' => true],
            ['name' => 'pay_period', 'label' => 'Pay Period', 'type' => 'text', 'required' => true],
            ['name' => 'basic_salary', 'label' => 'Basic Salary', 'type' => 'number'],
            ['name' => 'allowances', 'label' => 'Allowances', 'type' => 'number'],
            ['name' => 'deductions', 'label' => 'Deductions', 'type' => 'number'],
            ['name' => 'net_salary', 'label' => 'Net Salary', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Processed', 'Paid']],
        ],
        'columns' => ['employee_id', 'pay_period', 'net_salary', 'status'],
    ],
    'suppliers' => [
        'label' => 'Suppliers',
        'table' => 'suppliers',
        'route' => '/suppliers',
        'permissions' => ['Super Admin', 'Admin', 'Project Manager', 'Accountant'],
        'filters' => [
            ['name' => 'category', 'label' => 'Category', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Active', 'Inactive']],
        ],
        'fields' => [
            ['name' => 'name', 'label' => 'Supplier Name', 'type' => 'text', 'required' => true],
            ['name' => 'contact_person', 'label' => 'Contact Person', 'type' => 'text'],
            ['name' => 'mobile', 'label' => 'Mobile', 'type' => 'text'],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email'],
            ['name' => 'address', 'label' => 'Address', 'type' => 'textarea'],
            ['name' => 'category', 'label' => 'Category', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Active', 'Inactive']],
            ['name' => 'remarks', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['name', 'contact_person', 'category', 'mobile', 'status'],
    ],
    'materials' => [
        'label' => 'Materials',
        'table' => 'materials',
        'route' => '/materials',
        'permissions' => ['Super Admin', 'Admin', 'Project Manager', 'Site Engineer'],
        'filters' => [
            ['name' => 'category', 'label' => 'Category', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Active', 'Inactive']],
        ],
        'fields' => [
            ['name' => 'name', 'label' => 'Material Name', 'type' => 'text', 'required' => true],
            ['name' => 'category', 'label' => 'Category', 'type' => 'text'],
            ['name' => 'unit', 'label' => 'Unit', 'type' => 'text'],
            ['name' => 'unit_cost', 'label' => 'Rate', 'type' => 'number'],
            ['name' => 'stock_quantity', 'label' => 'Opening Stock', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Active', 'Inactive']],
        ],
        'columns' => ['name', 'category', 'unit', 'stock_quantity', 'status'],
    ],
    'inventories' => [
        'label' => 'Inventory',
        'table' => 'inventories',
        'route' => '/inventories',
        'permissions' => ['Super Admin', 'Admin', 'Project Manager', 'Site Engineer'],
        'fields' => [
            ['name' => 'material_id', 'label' => 'Material ID', 'type' => 'number'],
            ['name' => 'project_id', 'label' => 'Project ID', 'type' => 'number'],
            ['name' => 'quantity', 'label' => 'Quantity', 'type' => 'number'],
            ['name' => 'location', 'label' => 'Location', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Available', 'Reserved', 'Consumed']],
        ],
        'columns' => ['material_id', 'project_id', 'quantity', 'location', 'status'],
    ],
    'purchases' => [
        'label' => 'Purchases',
        'table' => 'purchases',
        'route' => '/purchases',
        'permissions' => ['Super Admin', 'Admin', 'Project Manager', 'Accountant'],
        'filters' => [
            ['name' => 'status', 'label' => 'Approval Status', 'type' => 'select', 'options' => ['Pending', 'Approved', 'Received']],
            ['name' => 'purchase_date', 'label' => 'Purchase Date', 'type' => 'date'],
        ],
        'fields' => [
            ['name' => 'supplier_id', 'label' => 'Supplier ID', 'type' => 'number'],
            ['name' => 'material_id', 'label' => 'Material ID', 'type' => 'number'],
            ['name' => 'purchase_date', 'label' => 'Purchase Date', 'type' => 'date', 'required' => true],
            ['name' => 'quantity', 'label' => 'Quantity', 'type' => 'number'],
            ['name' => 'amount', 'label' => 'Total Amount', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Approval Status', 'type' => 'select', 'options' => ['Pending', 'Approved', 'Received']],
            ['name' => 'remarks', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['supplier_id', 'material_id', 'purchase_date', 'amount', 'status'],
    ],
    'purchase_requests' => [
        'label' => 'Purchase Requests',
        'table' => 'purchase_requests',
        'route' => '/purchase-requests',
        'permissions' => ['Super Admin', 'Admin', 'Project Manager', 'Store Manager'],
        'filters' => [
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Requested', 'Approved', 'Declined']],
            ['name' => 'request_date', 'label' => 'Request Date', 'type' => 'date'],
        ],
        'fields' => [
            ['name' => 'requested_by', 'label' => 'Requested By', 'type' => 'text'],
            ['name' => 'material_id', 'label' => 'Material ID', 'type' => 'number'],
            ['name' => 'quantity', 'label' => 'Quantity', 'type' => 'number'],
            ['name' => 'request_date', 'label' => 'Request Date', 'type' => 'date'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Requested', 'Approved', 'Declined']],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'columns' => ['requested_by', 'material_id', 'quantity', 'request_date', 'status'],
    ],
    'purchase_orders' => [
        'label' => 'Purchase Orders',
        'table' => 'purchase_orders',
        'route' => '/purchase-orders',
        'permissions' => ['Super Admin', 'Admin', 'Project Manager', 'Accountant'],
        'filters' => [
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Issued', 'Received', 'Closed']],
            ['name' => 'order_date', 'label' => 'Order Date', 'type' => 'date'],
        ],
        'fields' => [
            ['name' => 'supplier_id', 'label' => 'Supplier ID', 'type' => 'number'],
            ['name' => 'material_id', 'label' => 'Material ID', 'type' => 'number'],
            ['name' => 'order_date', 'label' => 'Order Date', 'type' => 'date'],
            ['name' => 'expected_delivery', 'label' => 'Expected Delivery', 'type' => 'date'],
            ['name' => 'quantity', 'label' => 'Quantity', 'type' => 'number'],
            ['name' => 'amount', 'label' => 'Amount', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Issued', 'Received', 'Closed']],
            ['name' => 'remarks', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['supplier_id', 'material_id', 'order_date', 'quantity', 'status'],
    ],
    'purchase_bills' => [
        'label' => 'Purchase Bills',
        'table' => 'purchase_bills',
        'route' => '/purchase-bills',
        'permissions' => ['Super Admin', 'Admin', 'Accountant'],
        'filters' => [
            ['name' => 'bill_date', 'label' => 'Bill Date', 'type' => 'date'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'Verified', 'Paid']],
        ],
        'fields' => [
            ['name' => 'supplier_id', 'label' => 'Supplier ID', 'type' => 'number'],
            ['name' => 'purchase_order_id', 'label' => 'Purchase Order ID', 'type' => 'number'],
            ['name' => 'bill_date', 'label' => 'Bill Date', 'type' => 'date'],
            ['name' => 'amount', 'label' => 'Amount', 'type' => 'number'],
            ['name' => 'invoice_path', 'label' => 'Invoice File', 'type' => 'file'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'Verified', 'Paid']],
            ['name' => 'remarks', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['supplier_id', 'purchase_order_id', 'bill_date', 'amount', 'status'],
    ],
    'vendor_payments' => [
        'label' => 'Vendor Payments',
        'table' => 'vendor_payments',
        'route' => '/vendor-payments',
        'permissions' => ['Super Admin', 'Admin', 'Accountant'],
        'filters' => [
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'Paid', 'Overdue']],
            ['name' => 'paid_at', 'label' => 'Paid Date', 'type' => 'date'],
        ],
        'fields' => [
            ['name' => 'supplier_id', 'label' => 'Supplier ID', 'type' => 'number'],
            ['name' => 'purchase_bill_id', 'label' => 'Purchase Bill ID', 'type' => 'number'],
            ['name' => 'amount', 'label' => 'Amount', 'type' => 'number'],
            ['name' => 'payment_mode', 'label' => 'Payment Mode', 'type' => 'text'],
            ['name' => 'paid_at', 'label' => 'Paid Date', 'type' => 'datetime-local'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'Paid', 'Overdue']],
            ['name' => 'remarks', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['supplier_id', 'purchase_bill_id', 'amount', 'payment_mode', 'status'],
    ],
    'marketing_campaigns' => [
        'label' => 'Marketing Campaigns',
        'table' => 'marketing_campaigns',
        'route' => '/marketing-campaigns',
        'permissions' => ['Super Admin', 'Admin', 'Sales Manager', 'Marketing'],
        'filters' => [
            ['name' => 'channel', 'label' => 'Channel', 'type' => 'select', 'options' => ['Facebook', 'Instagram', 'Google Ads', 'YouTube', 'Email', 'SMS', 'WhatsApp']],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Planned', 'Active', 'Paused', 'Completed']],
        ],
        'fields' => [
            ['name' => 'name', 'label' => 'Campaign Name', 'type' => 'text', 'required' => true],
            ['name' => 'channel', 'label' => 'Channel', 'type' => 'select', 'options' => ['Facebook', 'Instagram', 'Google Ads', 'YouTube', 'Email', 'SMS', 'WhatsApp']],
            ['name' => 'start_date', 'label' => 'Start Date', 'type' => 'date'],
            ['name' => 'end_date', 'label' => 'End Date', 'type' => 'date'],
            ['name' => 'budget', 'label' => 'Budget', 'type' => 'number'],
            ['name' => 'spent', 'label' => 'Spent', 'type' => 'number'],
            ['name' => 'leads_generated', 'label' => 'Leads Generated', 'type' => 'number'],
            ['name' => 'roi', 'label' => 'ROI', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Planned', 'Active', 'Paused', 'Completed']],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'columns' => ['name', 'channel', 'start_date', 'end_date', 'status'],
    ],
    'social_posts' => [
        'label' => 'Social Media Posts',
        'table' => 'social_posts',
        'route' => '/social-posts',
        'permissions' => ['Super Admin', 'Admin', 'Sales Manager', 'Marketing'],
        'filters' => [
            ['name' => 'platform', 'label' => 'Platform', 'type' => 'select', 'options' => ['Facebook', 'Instagram', 'YouTube', 'LinkedIn', 'WhatsApp']],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Scheduled', 'Published']],
        ],
        'fields' => [
            ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true],
            ['name' => 'platform', 'label' => 'Platform', 'type' => 'select', 'options' => ['Facebook', 'Instagram', 'YouTube', 'LinkedIn', 'WhatsApp']],
            ['name' => 'scheduled_at', 'label' => 'Scheduled At', 'type' => 'datetime-local'],
            ['name' => 'content', 'label' => 'Content', 'type' => 'textarea'],
            ['name' => 'media_path', 'label' => 'Media File', 'type' => 'file'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Scheduled', 'Published']],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'columns' => ['title', 'platform', 'scheduled_at', 'status'],
    ],
    'material_inwards' => [
        'label' => 'Material Inwards',
        'table' => 'material_inwards',
        'route' => '/material-inwards',
        'permissions' => ['Super Admin', 'Admin', 'Project Manager', 'Site Engineer', 'Store Manager'],
        'filters' => [
            ['name' => 'received_date', 'label' => 'Received Date', 'type' => 'date'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Received', 'Pending', 'Rejected']],
        ],
        'fields' => [
            ['name' => 'material_id', 'label' => 'Material ID', 'type' => 'number'],
            ['name' => 'supplier_id', 'label' => 'Supplier ID', 'type' => 'number'],
            ['name' => 'received_date', 'label' => 'Received Date', 'type' => 'date'],
            ['name' => 'quantity', 'label' => 'Quantity', 'type' => 'number'],
            ['name' => 'warehouse_id', 'label' => 'Warehouse ID', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Received', 'Pending', 'Rejected']],
            ['name' => 'remarks', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['material_id', 'supplier_id', 'received_date', 'quantity', 'status'],
    ],
    'material_outwards' => [
        'label' => 'Material Outwards',
        'table' => 'material_outwards',
        'route' => '/material-outwards',
        'permissions' => ['Super Admin', 'Admin', 'Project Manager', 'Site Engineer', 'Store Manager'],
        'filters' => [
            ['name' => 'issued_date', 'label' => 'Issued Date', 'type' => 'date'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Issued', 'Returned']],
        ],
        'fields' => [
            ['name' => 'material_id', 'label' => 'Material ID', 'type' => 'number'],
            ['name' => 'project_id', 'label' => 'Project ID', 'type' => 'number'],
            ['name' => 'issued_date', 'label' => 'Issued Date', 'type' => 'date'],
            ['name' => 'quantity', 'label' => 'Quantity', 'type' => 'number'],
            ['name' => 'warehouse_id', 'label' => 'Warehouse ID', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Issued', 'Returned']],
            ['name' => 'remarks', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['material_id', 'project_id', 'issued_date', 'quantity', 'status'],
    ],
    'material_consumptions' => [
        'label' => 'Material Consumption',
        'table' => 'material_consumptions',
        'route' => '/material-consumptions',
        'permissions' => ['Super Admin', 'Admin', 'Project Manager', 'Site Engineer', 'Store Manager'],
        'filters' => [
            ['name' => 'consumed_date', 'label' => 'Consumed Date', 'type' => 'date'],
            ['name' => 'project_id', 'label' => 'Project', 'type' => 'number'],
        ],
        'fields' => [
            ['name' => 'material_id', 'label' => 'Material ID', 'type' => 'number'],
            ['name' => 'project_id', 'label' => 'Project ID', 'type' => 'number'],
            ['name' => 'consumed_date', 'label' => 'Consumed Date', 'type' => 'date'],
            ['name' => 'quantity', 'label' => 'Quantity', 'type' => 'number'],
            ['name' => 'used_by', 'label' => 'Used By', 'type' => 'text'],
            ['name' => 'remarks', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['material_id', 'project_id', 'consumed_date', 'quantity'],
    ],
    'warehouses' => [
        'label' => 'Warehouses',
        'table' => 'warehouses',
        'route' => '/warehouses',
        'permissions' => ['Super Admin', 'Admin', 'Project Manager', 'Store Manager'],
        'filters' => [
            ['name' => 'location', 'label' => 'Location', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Active', 'Inactive']],
        ],
        'fields' => [
            ['name' => 'name', 'label' => 'Warehouse Name', 'type' => 'text', 'required' => true],
            ['name' => 'location', 'label' => 'Location', 'type' => 'text'],
            ['name' => 'capacity', 'label' => 'Capacity', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Active', 'Inactive']],
            ['name' => 'notes', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['name', 'location', 'capacity', 'status'],
    ],
    'quality_checklists' => [
        'label' => 'Quality Checklists',
        'table' => 'quality_checklists',
        'route' => '/quality-checklists',
        'permissions' => ['Super Admin', 'Admin', 'Project Manager', 'Site Engineer'],
        'filters' => [
            ['name' => 'project_id', 'label' => 'Project ID', 'type' => 'number'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'Passed', 'Failed']],
        ],
        'fields' => [
            ['name' => 'project_id', 'label' => 'Project ID', 'type' => 'number'],
            ['name' => 'block', 'label' => 'Block', 'type' => 'text'],
            ['name' => 'floor', 'label' => 'Floor', 'type' => 'text'],
            ['name' => 'inspection_date', 'label' => 'Inspection Date', 'type' => 'date'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'Passed', 'Failed']],
            ['name' => 'remarks', 'label' => 'Remarks', 'type' => 'textarea'],
        ],
        'columns' => ['project_id', 'block', 'floor', 'inspection_date', 'status'],
    ],
    'project_blocks' => [
        'label' => 'Project Blocks',
        'table' => 'project_blocks',
        'route' => '/project-blocks',
        'permissions' => ['Super Admin', 'Admin', 'Project Manager', 'Site Engineer'],
        'fields' => [
            ['name' => 'project_id', 'label' => 'Project ID', 'type' => 'number'],
            ['name' => 'block_name', 'label' => 'Block Name', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Planning', 'Active', 'Completed']],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'columns' => ['project_id', 'block_name', 'status'],
    ],
    'project_floors' => [
        'label' => 'Project Floors',
        'table' => 'project_floors',
        'route' => '/project-floors',
        'permissions' => ['Super Admin', 'Admin', 'Project Manager', 'Site Engineer'],
        'fields' => [
            ['name' => 'project_id', 'label' => 'Project ID', 'type' => 'number'],
            ['name' => 'block_id', 'label' => 'Block ID', 'type' => 'number'],
            ['name' => 'floor_number', 'label' => 'Floor Number', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Planning', 'Active', 'Completed']],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'columns' => ['project_id', 'block_id', 'floor_number', 'status'],
    ],
    'employee_documents' => [
        'label' => 'Employee Documents',
        'table' => 'employee_documents',
        'route' => '/employee-documents',
        'permissions' => ['Super Admin', 'Admin', 'HR'],
        'filters' => [
            ['name' => 'employee_id', 'label' => 'Employee ID', 'type' => 'number'],
            ['name' => 'document_type', 'label' => 'Document Type', 'type' => 'text'],
        ],
        'fields' => [
            ['name' => 'employee_id', 'label' => 'Employee ID', 'type' => 'number'],
            ['name' => 'document_type', 'label' => 'Document Type', 'type' => 'text'],
            ['name' => 'file_path', 'label' => 'File', 'type' => 'file'],
            ['name' => 'issue_date', 'label' => 'Issue Date', 'type' => 'date'],
            ['name' => 'expiry_date', 'label' => 'Expiry Date', 'type' => 'date'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Active', 'Expired', 'Pending']],
            ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
        'columns' => ['employee_id', 'document_type', 'issue_date', 'expiry_date', 'status'],
    ],
    'holiday_calendars' => [
        'label' => 'Holiday Calendar',
        'table' => 'holiday_calendars',
        'route' => '/holiday-calendar',
        'permissions' => ['Super Admin', 'Admin', 'HR'],
        'fields' => [
            ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true],
            ['name' => 'holiday_date', 'label' => 'Holiday Date', 'type' => 'date', 'required' => true],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea'],
            ['name' => 'region', 'label' => 'Region', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Confirmed', 'Tentative']],
        ],
        'columns' => ['title', 'holiday_date', 'region', 'status'],
    ],
    'tasks' => [
        'label' => 'Tasks',
        'table' => 'tasks',
        'route' => '/tasks',
        'permissions' => ['Super Admin', 'Admin', 'Project Manager', 'Site Engineer', 'Supervisor'],
        'fields' => [
            ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true],
            ['name' => 'project_id', 'label' => 'Project ID', 'type' => 'number'],
            ['name' => 'assigned_to', 'label' => 'Assigned To', 'type' => 'text'],
            ['name' => 'due_date', 'label' => 'Due Date', 'type' => 'date'],
            ['name' => 'priority', 'label' => 'Priority', 'type' => 'select', 'options' => ['Low', 'Medium', 'High']],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'In Progress', 'Completed']],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea'],
        ],
        'columns' => ['title', 'assigned_to', 'due_date', 'priority', 'status'],
    ],
    'meetings' => [
        'label' => 'Meetings',
        'table' => 'meetings',
        'route' => '/meetings',
        'permissions' => ['Super Admin', 'Admin', 'Project Manager', 'Sales Manager', 'HR'],
        'fields' => [
            ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true],
            ['name' => 'meeting_date', 'label' => 'Meeting Date', 'type' => 'datetime-local', 'required' => true],
            ['name' => 'location', 'label' => 'Location', 'type' => 'text'],
            ['name' => 'attendees', 'label' => 'Attendees', 'type' => 'textarea'],
            ['name' => 'agenda', 'label' => 'Agenda', 'type' => 'textarea'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Scheduled', 'Completed', 'Cancelled']],
        ],
        'columns' => ['title', 'meeting_date', 'location', 'status'],
    ],
    'sop_templates' => [
        'label' => 'SOP Templates',
        'table' => 'sop_templates',
        'route' => '/sop-templates',
        'permissions' => ['Super Admin', 'Admin', 'HR', 'Project Manager'],
        'fields' => [
            ['name' => 'name', 'label' => 'Template Name', 'type' => 'text', 'required' => true],
            ['name' => 'category', 'label' => 'Category', 'type' => 'text'],
            ['name' => 'content', 'label' => 'Content', 'type' => 'textarea'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Active', 'Inactive']],
        ],
        'columns' => ['name', 'category', 'status'],
    ],
    'sops' => [
        'label' => 'SOPs',
        'table' => 'sops',
        'route' => '/sops',
        'permissions' => ['Super Admin', 'Admin', 'HR', 'Project Manager'],
        'fields' => [
            ['name' => 'template_id', 'label' => 'Template ID', 'type' => 'number'],
            ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true],
            ['name' => 'department', 'label' => 'Department', 'type' => 'text'],
            ['name' => 'owner', 'label' => 'Owner', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Approved', 'Published']],
            ['name' => 'content', 'label' => 'Content', 'type' => 'textarea'],
            ['name' => 'attachments', 'label' => 'Attachments', 'type' => 'text'],
        ],
        'columns' => ['title', 'department', 'owner', 'status'],
    ],
    'settings' => [
        'label' => 'Settings',
        'table' => 'settings',
        'route' => '/settings',
        'permissions' => ['Super Admin', 'Admin'],
        'fields' => [
            ['name' => 'key', 'label' => 'Setting Key', 'type' => 'text', 'required' => true],
            ['name' => 'value', 'label' => 'Value', 'type' => 'textarea'],
            ['name' => 'group', 'label' => 'Group', 'type' => 'text'],
        ],
        'columns' => ['key', 'group', 'value'],
    ],
    'audit_logs' => [
        'label' => 'Audit Logs',
        'table' => 'audit_logs',
        'route' => '/audit-logs',
        'permissions' => ['Super Admin', 'Admin'],
        'fields' => [
            ['name' => 'user_id', 'label' => 'User ID', 'type' => 'number'],
            ['name' => 'module', 'label' => 'Module', 'type' => 'text'],
            ['name' => 'action', 'label' => 'Action', 'type' => 'text'],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea'],
            ['name' => 'ip_address', 'label' => 'IP Address', 'type' => 'text'],
        ],
        'columns' => ['module', 'action', 'description', 'ip_address'],
    ],
];
